### ISSUE TITLE
why use torch.bmm as a packing op for matrix multiplication?

### ISSUE THREAD

**Issue by huangjundashuaige** [UofT-EcoSystem/hfta#36]
Hi,
As far as I know, bmm are usually used for launch hundreds of very small GEMMs, but in model packing setting, it feels bmm is not a perfect replacement for packing GEMM. Cound you share your insight why using bmm to packing GEMM?

**Comment by wangshangsam** [comment]
Hi @huangjundashuaige ,

Sorry for the late response. For some reason, GitHub didn't send me the email notification of this issue.

We know that large GEMMs usually utilize the hardware better than small GEMMs. If you have large GEMMs and already have good hardware utilization, you wouldn't need to bother with horizontal fusion. If you have small GEMMs and have poor hardware utilization, fusing them as a single BMM, even though it might not be the best possible solution ever, is almost always going to be better than launching each small GEMM separately (whether or not through multiple CUDA streams).

Theoretically speaking, we could also handwrite our own version of BMM that somehow biases towards the use case when the "batch" dimension is relatively small and the two matrix dimensions are relatively large. You can even be fancier by leveraging and tuning the BMM from TVM for specific dimensions of specific models, and somehow plugging the tuned kernel back into PyTorch.

However, simply using bmm from PyTorch (i.e., ultimately from cuBLAS) is easier (to a point that a "pure" ML person without in-depth GPU knowledge, the targeted user group of HFTA, can make sense of it). It also turned out to have decent performance (at least on V100 and A100) - we actually tried the TVM approach in a slightly different context, and very often cuBLAS does better in our micro-benchmarks. Thus, we just went with the easier approach.

**Comment by wangshangsam** [comment]
Closing this issue now. @huangjundashuaige feel free to let us know if you have further questions!
